// <auto-generated />
namespace HappySquad.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class DelText : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DelText));
        
        string IMigrationMetadata.Id
        {
            get { return "201301041217411_delText"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
